делает то же самое, но не делает повторов и читаемо
AnatolyDomrachev/1kurs pull request #1
Opened 2020-09-14 14:57 UTC by kesha1225

2020-09-14 15:03 UTC, prostomarkeloff requested changes
Не хватает аннотаций типов (или иначе - тайп хинтов).

2020-09-14 15:49 UTC, gabbhack approved these changes

2020-09-14 15:52 UTC, prostomarkeloff commented
габбхак не человек.

2020-09-14 15:52 UTC, prostomarkeloff commented
боже, убей габбхака.

2020-09-16 02:28 UTC, AnatolyDomrachev approved these changes

2020-09-16 02:29 UTC, merged

2020-09-16 02:29 UTC, AnatolyDomrachev commented
1

2020-09-24 07:56 UTC, catofsof commented
2